language: d
d: dmd-2.091.0

before_install:
  - sudo apt-get -y install libfuse2 libfuse-dev

install:
  - wget -O doveralls "https://github.com/ColdenCullen/doveralls/releases/download/v1.3.2/doveralls_linux_travis"
  - chmod +x doveralls

script:
  - t/all.sh
  - find t/tmp/cov -type f -not -name thincow.lst -delete
  - ./doveralls
